# .github/workflows/release.yml

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup (Install Node & pnpm)
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build CLI & Publish to npm
        run: pnpm --filter shadcn-vue pub:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Module & Publish to npm
        run: pnpm --filter shadcn-nuxt pub:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
